server:
  port: 3344
spring:
  application:
    name: cloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: git@gitee.com:clown121381/cloud-config-yml.git
#          force-pull: true